images:
  imagePath: "/root/mydocker/images"
rootfs:
  rootfsPath: "/root/mydocker/rootfs"
  workLayerPath: "/root/mydocker/rootfs/work"
  upperLayerPath: "/root/mydocker/rootfs/upper"
  mntLayerPath: "/root/mydocker/rootfs/mnt"
  mntOldPath: ".old"
version: "0.0.1"